local io performance blog
NREL/HPC pull request #250
Opened 2022-12-28 21:12 UTC by tdthatcher

Adds "local I/O performance" discussion from March 2022 as a blog entry.

2023-01-25 19:07 UTC, mcfarljm commented on docs/blog/2022-03-05-local-io-performance.md
> +Eagle also has two storage options on the compute nodes. /dev/shm, is an in-memory space (shm: shared memory), which is fast, but you need to balance its usage with your jobs memory usage as it is lo
```suggestion
Eagle also has two storage options on the compute nodes. /dev/shm is an in-memory space (shm: shared memory), which is fast, but you need to balance its usage with your job's memory usage as it is located directly in RAM. /tmp/scratch is physical storage. The type of storage and performance differ depending on the specific type of compute node. 
```

2023-01-25 19:11 UTC, mcfarljm approved these changes
LGTM, just some minor edits.

2023-01-25 19:11 UTC, mcfarljm commented on docs/blog/2022-03-05-local-io-performance.md
> +If we look under Eagle's [Compute Node Hardware Details](https://www.nrel.gov/hpc/eagle-system-configuration.html) on the central [NREL HPC website](https://www.nrel.gov/hpc), there are nodes listed
For consistent usage of plural acronyms:
```suggestion
If we look under Eagle's [Compute Node Hardware Details](https://www.nrel.gov/hpc/eagle-system-configuration.html) on the central [NREL HPC website](https://www.nrel.gov/hpc), there are nodes listed as having SATA drives, and nodes listed as having SSDs. Our SATA drives are still spinning disks, while SAS (serial attached SCSI) is how the SSDs are connected to the node. We would generally expect the nodes with SSDs to perform better. Let’s test that out with a simple test. 
```

2023-02-21 16:37 UTC, yandthj requested changes
Minor fix needed for consistent usage of acronyms

2023-02-22 17:15 UTC, tdthatcher commented
fixed plural/possessive issue.

2023-02-22 19:00 UTC, yandthj submitted a review, later dismissed

2023-02-22 19:01 UTC, yandthj approved these changes

2023-02-22 19:01 UTC, merged