"Running on Swift" page updates
NREL/HPC pull request #256
Opened 2023-01-25 19:03 UTC by tdthatcher

Rework of "Running on Swift" page with AU charge clarifications, partition info, spelling/grammar fixes

2023-02-15 16:40 UTC, yandthj requested changes

2023-02-15 16:40 UTC, yandthj commented on docs/Documentation/Systems/Swift/running.md
> -**There are currently a number of known issues on Swift please check [Known issues](./known.md) for a complete list**
Should the known issues page be removed all together?

2023-02-22 17:13 UTC, tdthatcher commented on docs/Documentation/Systems/Swift/running.md
> +Multiple software environments are available on Swift, with a number of commonly used modules including compilers, common build tools, specific AMD optimized libraries, and some analysis tools. The e
Fixed with new commit, thank you.

2023-02-22 18:26 UTC, yandthj approved these changes

2023-02-22 18:37 UTC, yandthj approved these changes

2023-02-22 18:37 UTC, merged