Update content for anaconda
NREL/HPC pull request #369
Opened 2023-03-20 18:38 UTC by mcfarljm

Per separate discussions, the general plan is to place the documentation for conda in a single location, Environment/Customization.  The conda section under Development/Languages/Python has been removed.  Most of the existing conda content was quite good, so I've mostly kept it as is, with some minor updates to formatting and to use more general language about the HPC systems (instead of just Eagle).

I've also removed Development/Languages/NREL_python.md, and ported a simplified version of the relevant content (about where to store environments) to conda.md.

2023-03-31 00:09 UTC, harrysorensennrel approved these changes

2023-04-25 14:47 UTC, yandthj requested changes
Minor typo, otherwise looks good

2023-04-25 14:47 UTC, yandthj commented on docs/Documentation/Environment/Customization/conda.md
> +| `\home` | `$HOME/.conda` is the default location for environments. For one-off environments, or if you don't create environments often, this is a reasonable location for your environments and doesn
```suggestion
| `/home` | `$HOME/.conda` is the default location for environments. For one-off environments, or if you don't create environments often, this is a reasonable location for your environments and doesn't require any extra flags or parameters.            | On systems such as Eagle, `$HOME` is limited to 50 GB.         |
```

2023-04-25 14:59 UTC, yandthj approved these changes

2023-04-25 15:00 UTC, merged