Kestrel updates for "build your own package" section
NREL/HPC pull request #493
Opened 2023-09-12 16:38 UTC by arswalid

- Index updated to include Kestrel
- Renaming of each sub-page
- Edits to the example to cover Kestrel

2023-09-12 16:39 UTC, arswalid commented
tied to issue https://github.com/NREL/HPC/issues/343

2023-09-13 20:52 UTC, yandthj requested changes

2023-09-13 20:52 UTC, yandthj commented on docs/Documentation/Environment/Building_Packages/config_make_install.md
> +Other build systems like `CMake` (which differ primarily in the configuration steps) won't be covered.
Since we have a CMake page now, could link to that

2023-09-13 20:52 UTC, yandthj commented on docs/Documentation/Environment/Building_Packages/modules.md
>  	[cchang@el1 ~]$ module avail
```suggestion
	[$USER@el1 ~]$ module avail
```

2023-09-13 20:52 UTC, yandthj commented on docs/Documentation/Environment/Building_Packages/config_make_install.md
> +title: Config,Make,Install
```suggestion
title: Config, Make, Install
```

2023-09-13 20:52 UTC, yandthj commented on docs/Documentation/Environment/Building_Packages/acquire.md
> +You can either download it to a local machine (laptop) and then `scp` the file over to Kestrel/Eagle, or get it directly on Kestrel/Eagle with `wget`.
Could probably make this page all generic, instead of "Eagle/Kestrel" just "HPC system" or something similar

2023-09-19 21:23 UTC, yandthj commented on docs/Documentation/Environment/Building_Packages/acquire.md
> +You can either download it to a local machine (laptop) and then `scp` the file over to the HPC cluster, or get it directly on the superomuter using `wget`.
```suggestion
You can either download it to a local machine (laptop) and then `scp` the file over to the HPC cluster, or get it directly on the supercomputer using `wget`.
```

2023-09-19 21:23 UTC, yandthj approved these changes

2023-09-19 21:24 UTC, merged