Update gaussian.md
NREL/HPC pull request #506
Opened 2023-09-26 17:11 UTC by sinolonghai

With some cosmetic changes

2023-09-28 17:47 UTC, yandthj requested changes
Thanks for the update Hai. Just made a note about changing the "hpcapps" allocation in an example submit script. Would you recommend running Gaussian on the Kestrel nodes with NVMe?

2023-10-04 17:53 UTC, sinolonghai commented
Hi Hayley, 

What does it mean that "Would you recommend running Gaussian on the Kestrel nodes with NVMe?" I remember all Kestrel nodes have NVMe, or this is not correct?

Hai

2023-10-04 20:49 UTC, yandthj commented
> Hi Hayley,
> 
> What does it mean that "Would you recommend running Gaussian on the Kestrel nodes with NVMe?" I remember all Kestrel nodes have NVMe, or this is not correct?
> 
> Hai

Only the bigmem nodes and 256 of the standard compute nodes do.

2023-11-10 19:06 UTC, yandthj submitted a review, later dismissed

2023-11-10 19:07 UTC, yandthj approved these changes

2023-11-10 19:07 UTC, merged