Update scripts and instructions for Kestrel
NREL/HPC pull request #586
Opened 2024-02-16 23:01 UTC by daniel-thom

There are two sets of changes in this pull request:
1. Update paths, commands, and instructions for Kestrel. There are also some general documentation improvements.
2. Add the new script, `configure_and_start_spark.sh`, to allow the user to get the cluster running in a single command instead of three. The actual functionality didn’t change much.

I have tested the scripts on Eagle and Kestrel. The included test runs on Kestrel.

2024-02-20 17:46 UTC, k1nshuk requested changes
The content looks good. It only needs to be broken into 2 different branches. Typically, most of the "documentation", i.e., markdown files go into gh-pages where as the run scripts go into master. There can be some readme files in master that basically describes what files in master do

2024-02-20 17:46 UTC, k1nshuk commented on applications/spark/README.md
@daniel-thom We have moved to a different format where the instructions and documentation is now hosted in a separate branch called [gh-pages](https://github.com/NREL/HPC/tree/gh-pages), that creates nicer looking documentation visible on https://nrel.github.io/HPC/. You should be able to simply copy paste this into the different branch.

2024-02-20 17:46 UTC, k1nshuk commented on applications/spark/README.md
> +Standard nodes do not have local storage and are unsuitable if you will shuffle data. By default,
```suggestion
By default,
```

2024-02-20 17:46 UTC, k1nshuk commented on applications/spark/README.md
> +Kestrel has 256 nodes with local SSDs. Pick those if you can. For example, `salloc --tmp=1600G`.
I think we should start this section with this. there is no concept of "standard" nodes
```suggestion
Kestrel only has 256 nodes with local SSDs out of the 2144 CPU-only nodes available. 
Pick those if you can. For example, `salloc --tmp=1600G`.
```

2024-02-20 17:46 UTC, k1nshuk commented on applications/spark/README.md
> +**Note**: The only way to customize Spark worker parameters is by editing `conf/spark-env.sh`.
Once you migrate this to the gh-pages branch, we will need to change the notes to use [admonitions](https://docusaurus.io/docs/markdown-features/admonitions).

2024-02-20 17:46 UTC, k1nshuk commented on applications/spark/docker/python/Dockerfile
These docker files can remain in master

2024-02-20 17:46 UTC, k1nshuk commented on applications/spark/python.md
Needs to be moved into gh-pages

2024-02-20 17:46 UTC, k1nshuk commented on applications/spark/slurm_scripts/batch_job.sh
appropriate for master

2024-02-22 23:49 UTC, daniel-thom commented on applications/spark/README.md
@k1nshuk Just to confirm, are you saying that I should open a second PR that is based off the gh-pages branch? That seems to me to be an unusual workflow (https://www.mkdocs.org/user-guide/deploying-your-docs/#project-pages).

I had been under the impression that these scripts were useful but not necessarily “official”, and so the instructions were buried next to the scripts. I am certainly OK with them becoming official but am concerned about the requirement that the user clone the repository to get the scripts. Is that typical here? Should I create an environment module instead? That could lead to maintenance problems if I am not around to do that. I’ll take your advice here.

2024-02-23 01:21 UTC, daniel-thom commented on applications/spark/r.md
It seems like what you want is one Markdown file called `docs/Documentation/Applications/apache_spark.md`. I can include sections in that file for Python and R. I originally split them out to be easier to read, but have no problem with this.

2024-02-23 15:57 UTC, yandthj approved these changes

2024-02-28 19:27 UTC, yandthj approved these changes

2024-02-28 19:28 UTC, merged