Addition of Amr-wind build instructions
NREL/HPC pull request #608
Opened 2024-04-09 16:09 UTC by arswalid

2024-04-10 20:18 UTC, yandthj requested changes

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +https://github.com/Exawind/amr-wind
Add link text, "[the AMR-Wind documentation](https://github.com/Exawind/amr-wind)" for example

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +AMR-wind can be installed by following the instructions [Here](https://exawind.github.io/amr-wind/user/build.html#building-from-source) .
```suggestion
AMR-wind can be installed by following the instructions [here](https://exawind.github.io/amr-wind/user/build.html#building-from-source).
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +ON Kestrel GPU nodes, this can be achieved by first loading the following modules:
```suggestion
On Kestrel GPU nodes, this can be achieved by first loading the following modules:
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +Make sure the following modules are loaded using module list.
```suggestion
Make sure the following modules are loaded using `module list`.
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +  1) libfabric/1.15.2.0
For list formatting, use "." instead of ")" and no extra space in between lines. For example:
1.
2.

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +you can clone the latest version of AMR-wind from [here](https://github.com/Exawind/amr-wind?tab=readme-ov-file).
```suggestion
You can clone the latest version of AMR-wind from [here](https://github.com/Exawind/amr-wind?tab=readme-ov-file).
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +you can create a file with the cmake instructions,
```suggestion
You can create a file with the cmake instructions, 
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +you can execute the file using
```suggestion
You can execute the file using 
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +NREL makes available different modules for using Amr-Wind for CPUs and GPUs for
```suggestion
NREL makes available different modules for using AMR-Wind for CPUs and GPUs for
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +different toolchains. The build instructions are given below for users wanting to build there own version. It is recommended that
```suggestion
different toolchains. The build instructions are given below for users wanting to build their own version. It is recommended that
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/amrwind.md
> +Here is a sample script for submitting an AMR-Wind application run on multiple GPU nodes, with the users input file, mesh grid in the current working directory.
```suggestion
Here is a sample script for submitting an AMR-Wind application run on multiple GPU nodes, with the user's input file and mesh grid in the current working directory.
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/openfoam.md
> +OpenFoam installation
```suggestion
OpenFoam Installation 
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/openfoam.md
> +Instruction for the installing OpenFoam are available [here](https://openfoam.org/download/source/).
```suggestion
Instructions for installing OpenFoam are available [here](https://openfoam.org/download/source/).
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/openfoam.md
> +In the instruction, you will be cloning the OpenFoam folder which we will refere to as `$OPENFOAM`.
```suggestion
In the instructions, you will be cloning the OpenFoam folder which we will refer to as `$OPENFOAM`.
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/openfoam.md
> +Searhc for the line where the varibale is exported and replace it with
```suggestion
Search for the line where the variable is exported and replace it with 
```

2024-04-10 20:18 UTC, yandthj commented on docs/Friendly_User/Applications/openfoam.md
> +OpenFoam installation
Need to add the OpenFoam file to the nav section in mkdocs.yml

2024-04-23 18:51 UTC, yandthj reviewed
Should OpenFoam be added to the GPU Friendly Users, or the main applications section? It needs to be added to the nav section in the mkdocs.yml file in either case

2024-04-23 19:23 UTC, arswalid commented
Hi Haley, 
I was thinking GPU Friendly Users page

2024-04-23 19:53 UTC, yandthj approved these changes

2024-04-23 19:54 UTC, merged