Update Ansys Documentation
NREL/HPC pull request #696
Opened 2024-10-22 22:17 UTC by xinhe2205

2024-10-22 22:18 UTC, xinhe2205 commented
Update Ansys documentation

2024-10-24 15:26 UTC, yandthj requested changes

2024-10-24 15:48 UTC, xinhe2205 commented on docs/Documentation/Applications/ansys.md
> +#SBATCH --qos=high
It is removed.

2024-10-24 15:48 UTC, xinhe2205 commented on docs/Documentation/Applications/ansys.md
> +##SBATCH --exclusive
It is removed.

2024-10-24 15:48 UTC, xinhe2205 commented on docs/Documentation/Applications/ansys.md
> +#SBATCH --account=your_account
Revised to be <your_account>.

2024-10-24 15:49 UTC, xinhe2205 commented on docs/Documentation/Applications/ansys.md
> +#SBATCH --account=your_account
revised.

2024-10-24 15:49 UTC, xinhe2205 commented on docs/Documentation/Applications/ansys.md
> +##SBATCH --exclusive
It is removed.

2024-10-24 15:49 UTC, xinhe2205 commented on docs/Documentation/Applications/ansys.md
> +When running Ansys job, the out of memory error is commonly encountered. To overcome the out of memory issue you can try the following  a few things:
Revised based on what you suggested.

2024-10-24 15:50 UTC, xinhe2205 commented on docs/Documentation/Applications/ansys.md
> +At NREL, a few groups own their own Ansys license. In order to connect to the private license, the user can set the environment variable `ANSYSLMD_LICENSE_FILE` (e.g. `export ANSYSLMD_LICENSE_FILE=10
Revised accordingly.

2024-10-24 15:50 UTC, xinhe2205 commented
Hi Haley,

Thank you for reviewing it. I have revised it based on each of your comments. 

Thanks,
Xin

2024-10-24 16:08 UTC, merged