Intel parallel studio (update)
NREL/HPC pull request #712
Opened 2024-12-02 17:52 UTC by arswalid

2024-12-02 19:10 UTC, yandthj requested changes

2024-12-02 19:10 UTC, yandthj commented on docs/Documentation/Development/Performance_Tools/Intel/index.md
> -When using the suite of tools from Intel Parallel Studio on Eagle, we recommend that you set your `TMPDIR` to point to a location in your `SCRATCH` directory:
Do you not recommend this on Kestrel?

2024-12-02 19:10 UTC, yandthj commented on docs/Documentation/Development/Performance_Tools/Intel/index.md
>  `export TMPDIR=/scratch/$USER/tmp`
This line should be removed too if removing the line above

2024-12-02 19:48 UTC, arswalid commented on docs/Documentation/Development/Performance_Tools/Intel/index.md
> -When using the suite of tools from Intel Parallel Studio on Eagle, we recommend that you set your `TMPDIR` to point to a location in your `SCRATCH` directory:
fixed

2024-12-03 17:44 UTC, yandthj approved these changes

2024-12-03 17:45 UTC, merged